export {default as shoe1} from "./images/shoes.svg"
export {default as shoe2} from "./images/2.svg"
export {default as shoe3} from "./images/3.svg"
export {default as shoe4} from "./images/4.svg"
export {default as plus} from "./images/Solid/plus.svg"
export {default as minus} from "./images/Purple.svg"
export {default as shoes} from "./images/shoes.svg"
export {default as basket} from "./images/Shape (1).svg"